name: Release integration pipeline

on:
  release:
    types:
      - prereleased
      - released
    tags:
      - 'v*'

jobs:
  integration-release:
    name: Use goreleaser for releasing
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2.1.5
        with:
          credentials_json: ${{ secrets.GIT_DEPLOYER_KEY }}
      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/plateng-resources-5ccd0b11/armory-docker/nri-prometheus:latest .
          docker push us-central1-docker.pkg.dev/plateng-resources-5ccd0b11/armory-docker/nri-prometheus:latest
